CREATE TABLE PARAM (
    TEMPLATE_NAME    CHARACTER VARYING(200)
  , PARAM_NAME       CHARACTER VARYING(50)
  , PARAM_DESC       CHARACTER VARYING(250)
  , PARAM_DEFAULT    CHARACTER VARYING(1000)

  , primary key ( TEMPLATE_NAME , PARAM_NAME )
);
