CREATE TABLE PROCESSING_GROUP_SET_MEMBERS (
    PROCESSING_GROUP_SET_NAME    CHARACTER VARYING(200)    not null
  , PROCESSING_GROUP_NAME        CHARACTER VARYING(200)    not null

  , primary key ( PROCESSING_GROUP_SET_NAME , PROCESSING_GROUP_NAME )
);
